#!/usr/bin/env bash
if [ `id -u` != 0 ]; then
  echo "Error: config_fail2ban must be executed by root"
  exit -1
fi

cat <<EOL >> /etc/fail2ban/jail.local
[DEFAULT]
bantime = 3600
maxretry = 3 

[sshd]
enabled = true
banaction = iptables-multiport

[postfix]
enabled = true

EOL

systemctl restart fail2ban
