#!/usr/bin/env bash
if [ `id -u` != 0 ]; then
  echo "Error: create_admin script must be executed by root"
  exit -1
fi

USERNAME=$1
PASSCHARS="a-zA-Z0-9!@#$%&,._"
P="$(head -c 100 /dev/urandom | tr -dc $PASSCHARS )"
PASSWD="${P:0:16}"
echo "Adding admin user (sudoer) $USERNAME with password '$PASSWD'"
useradd -G wheel -m $USERNAME
echo "$PASSWD" | passwd --stdin $USERNAME
