#!/usr/bin/env bash
if [ `id -u` != 0 ]; then
  echo "Error: install_fail2ban must be executed by root"
  exit -1
fi

yum -y install epel-release
yum -y install fail2ban
systemctl enable fail2ban
systemctl start fail2ban

